export const patients = [
  {
    id: 1,
    name: "PRANAY D BHADORIA",
    opdId: "1445953",
    visitDate: "2025-11-05 12:00:42",
    age: 34,
    gender: "Male",
    lastVisit: "2025-11-01",
    totalVisits: 10,
    chronicConditions: "Hypertension",
    recentComplaint: "Headache, occasional dizziness",
    medications: "Amlodipine 5mg",
    allergies: "None",
    doctorNotes: "Blood pressure improving; continue same dose.",
  },
  {
    id: 2,
    name: "RIYA K MEHTA",
    opdId: "1445954",
    visitDate: "2025-11-05 12:15:20",
    age: 29,
    gender: "Female",
    lastVisit: "2025-10-20",
    totalVisits: 5,
    chronicConditions: "Asthma",
    recentComplaint: "Shortness of breath on exertion",
    medications: "Salbutamol inhaler PRN",
    allergies: "Dust mites",
    doctorNotes: "Advise regular follow-up and inhaler technique review.",
  },
  {
    id: 3,
    name: "MOHIT SINGH",
    opdId: "1445955",
    visitDate: "2025-11-05 12:25:10",
    age: 32,
    gender: "Male",
    lastVisit: "2025-11-01",
    totalVisits: 12,
    chronicConditions: "Diabetes Type 2",
    recentComplaint: "Numbness in feet",
    medications: "Metformin 500mg",
    allergies: "None",
    doctorNotes: "Sugar levels controlled; neuropathy symptoms mild.",
  },
  {
    id: 4,
    name: "ANITA RATHOD",
    opdId: "1445956",
    visitDate: "2025-11-05 12:45:32",
    age: 45,
    gender: "Female",
    lastVisit: "2025-10-10",
    totalVisits: 8,
    chronicConditions: "Thyroid Disorder",
    recentComplaint: "Fatigue and weight gain",
    medications: "Levothyroxine 50mcg",
    allergies: "None",
    doctorNotes: "Adjust dose based on next thyroid profile report.",
  },
  {
    id: 5,
    name: "HARDIK PATEL",
    opdId: "1445957",
    visitDate: "2025-11-05 13:05:11",
    age: 38,
    gender: "Male",
    lastVisit: "2025-09-25",
    totalVisits: 3,
    chronicConditions: "None",
    recentComplaint: "Acute lower back pain",
    medications: "NSAIDs as prescribed",
    allergies: "None",
    doctorNotes: "Physiotherapy advised; review in two weeks.",
  },
];
