export const correctedSamplesTrend = [
  {
    dateLabel: "11/03/2024",
    transcriptChanges: 0,
    diagnosisChanges: 1,
    subjectiveChanges: 0.5,
    objectiveChanges: 0,
    assessmentChanges: 0,
    planChanges: 0.5,
  },
  {
    dateLabel: "13/03/2024",
    transcriptChanges: 0,
    diagnosisChanges: 0.5,
    subjectiveChanges: 0,
    objectiveChanges: 0.3,
    assessmentChanges: 0,
    planChanges: 0,
  },
  {
    dateLabel: "17/10/2024",
    transcriptChanges: 2,
    diagnosisChanges: 1,
    subjectiveChanges: 1,
    objectiveChanges: 0.3,
    assessmentChanges: 0.2,
    planChanges: 0.5,
  },
  {
    dateLabel: "18/10/2024",
    transcriptChanges: 1.8,
    diagnosisChanges: 1,
    subjectiveChanges: 1,
    objectiveChanges: 0.2,
    assessmentChanges: 0.2,
    planChanges: 0.3,
  },
  {
    dateLabel: "21/04/2025",
    transcriptChanges: 1,
    diagnosisChanges: 0.6,
    subjectiveChanges: 0.7,
    objectiveChanges: 0.1,
    assessmentChanges: 0.1,
    planChanges: 0.2,
  },
  {
    dateLabel: "06/06/2025",
    transcriptChanges: 0.4,
    diagnosisChanges: 0.3,
    subjectiveChanges: 0,
    objectiveChanges: 0.1,
    assessmentChanges: 0,
    planChanges: 0,
  },
  {
    dateLabel: "29/07/2025",
    transcriptChanges: 0.5,
    diagnosisChanges: 0.2,
    subjectiveChanges: 0.3,
    objectiveChanges: 0,
    assessmentChanges: 0.1,
    planChanges: 0,
  },
  {
    dateLabel: "12/08/2025",
    transcriptChanges: 1,
    diagnosisChanges: 0.8,
    subjectiveChanges: 0.9,
    objectiveChanges: 0.2,
    assessmentChanges: 0.2,
    planChanges: 0.3,
  },
  {
    dateLabel: "20/11/2025",
    transcriptChanges: 1.5,
    diagnosisChanges: 0.7,
    subjectiveChanges: 0.8,
    objectiveChanges: 0.3,
    assessmentChanges: 0.3,
    planChanges: 0.4,
  },
  {
    dateLabel: "27/11/2025",
    transcriptChanges: 2,
    diagnosisChanges: 1,
    subjectiveChanges: 1,
    objectiveChanges: 0.4,
    assessmentChanges: 0.4,
    planChanges: 0.6,
  },
];

export const editingBreakdown = [
  { name: "transcript", value: 30 },
  { name: "diagnosis", value: 25 },
  { name: "subjective", value: 15 },
  { name: "objective", value: 10 },
  { name: "assessment", value: 8 },
  { name: "plan", value: 12 },
];
